apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "roots-front.fullname" . }}
  labels:
    {{- include "roots-front.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "roots-front.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "roots-front.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "roots-front.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_HOST
              value: {{ .Values.imagePullSecrets.postgresSqlSS }}
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DBNAME
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PASSWORD
                  name: {{ .Values.imagePullSecrets.postgresSecretName }}

          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          livenessProbe:
                exec:
                  command:
                  - /bin/sh 
                  - "-c"
                  - | 
                          wget -qO- --header="Origin: http://localhost:3000" http://localhost:9000/api/health &> /dev/null
          readinessProbe:
               exec:
                  command:
                  - /bin/sh
                  - "-c"   
                  - | 
                   wget -qO- --header="Origin: http://localhost:3000" http://localhost:9000/api/health &> /dev/null
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
