name: Release Version

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  release_version:
    name: Release Version
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set vars 
        run: echo "KUBECONFIG=\".k3s.yaml\"" >> $GITHUB_ENV

      # - name: override kubectl config file 
      #   run: |
      #     cat .k3s.yaml
      #     cat ${GITHUB_WORKSPACE}/.k3s.yaml
      #     export KUBECONFIG=${GITHUB_WORKSPACE}/.k3s.yaml
      #     # cp  ${GITHUB_WORKSPACE}/.k3s.yaml ~/.kube/config

      - name: Set tag env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push image 
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: adihaimsohn/roots-back:dev.${{ github.sha }}
          file: Dockerfile.prod
#          tags: dorsivan/roots-back:dev.${{ github.sha }}
      
      # - name: try to set permissions
      #   run: chown 644 .k3s.yaml

      - name: helm upgrade 
        run: | 
          ls -la
          pwd
          KUBECONFIG=.k3s.yaml helm upgrade back ci/k3s/roots-back/ --install --values=ci/k3s/roots-back/values.yaml --set image.tag=dev.${{ github.sha }}




